language: java
jdk:
  - openjdk8

script:
#  - mvn clean package
  - sudo useradd lsfadmin && sudo usermod -aG docker lsfadmin
  - sudo mkdir -p /opt/ibm
  - docker pull ibmcom/lsfce:10.2.0
  - docker run --rm -v /opt/ibm/:/hostibm --entrypoint=/bin/cp ibmcom/lsfce:10.2.0 -rf /opt/ibm/lsfsuite/lsf /start_lsf_ce.sh /hostibm
  - sudo chown -R travis:traivs /opt/ibm/*
  - conformance/test.sh

