language: java
jdk:
  - openjdk8

script:
  - mvn clean package
  - useradd lsfadmin && usermod -aG docker lsfadmin
  - docker pull ibmcom/lsfce:10.2.0
  - ls /opt
#  - docker build -t cwlexec-test -f conformance/Dockerfile .
#  - docker run -v /var/run/docker.sock:/var/run/docker.sock cwlexec-test

