language: java
jdk:
  - openjdk8

before_install:
  - sudo apt update
  - sudo apt install -y python3 python3-setuptools python3-pip
  - sudo pip3 install cwltest

script:
  - mvn clean package
#  - sudo useradd lsfadmin && sudo usermod -aG docker lsfadmin
  - sudo mkdir -p /opt/ibm/lsfsuite
#  - docker run --rm -v /opt/ibm/lsfsuite:/ibmtop -v $(pwd)/conformance/config.sh:/config.sh --entrypoint=/config.sh ibmcom/lsfce:10.2.0 `uname -n`
#  - sudo chown -R lsfadmin:lsfadmin /opt/ibm/*
#  - sudo -s conformance/start.sh
#  - sudo chown -R lsfadmin:lsfadmin ../cwlexec
  - ls -l ..
  - ls -l target
#  - sudo su lsfadmin bash -c conformance/test.sh
  - conformance/test.sh

