language: java
jdk:
  - openjdk8

script:
  - mvn clean package
  - docker build --build-arg CWLTOP=${PWD} -t cwlexec-test conformance/
  - docker run -v /var/run/docker.sock:/var/run/docker.sock cwlexec-test

