language: java
jdk:
  - openjdk8

script:
#  - mvn clean package
  - sudo useradd lsfadmin && sudo usermod -aG docker lsfadmin
  - sudo mkdir -p /opt/ibm
#  - docker build -t cwlexec-test -f conformance/Dockerfile .
  - docker run --rm -v /opt/ibm/:/hostibm -v $(pwd)/conformance/test.sh:/test.sh --entrypoint=/test.sh ibmcom/lsfce:10.2.0
#  - docker pull ibmcom/lsfce:10.2.0
#  - docker run --rm -v /opt/ibm/:/hostibm --entrypoint=/bin/cp ibmcom/lsfce:10.2.0 -rf /opt/ibm/lsfsuite/lsf /start_lsf_ce.sh /hostibm
  - sudo chown -R lsfadmin:lsfadmin /opt/ibm/*
  - cat /opt/ibm/lsf/conf/lsf.conf
  - cat /opt/ibm/lsf/conf/lsf.shared
  - cat /opt/ibm/lsf/conf/lsf.cluster.cluster1
#  - conformance/test.sh

