language: java
jdk:
  - openjdk8

script:
#  - mvn clean package
  - sudo useradd lsfadmin && sudo usermod -aG docker lsfadmin
  - sudo mkdir -p /opt/ibm
  - docker run --rm -v /opt/ibm/:/hostibm -v $(pwd)/conformance/test.sh:/test.sh --entrypoint=/test.sh ibmcom/lsfce:10.2.0 `uname -n`
  - sudo chown -R lsfadmin:lsfadmin /opt/ibm/*
  - sudo -s && source /opt/ibm/lsf/conf/profile.lsf && lsadmin limstartup && lsadmin resstartup && badmin hstartup
  - sleep 10
  - lsid && bhosts
#  - conformance/test.sh

